---
title: "Iteration"
subtitle : "Function"
output: github_document
---

```{r setup}
library(tidyverse)
library(rvest)
```

## Do Something Simple

```{r}
x_vec <- rnorm(30, mean = 5, sd = 3)

(x_vec - mean(x_vec)) / sd(x_vec)
```

I want a function to compute Z score

```{r}
z_score <- function(x) {
  
  if (!is.numeric(x)) {
    stop("Input must be numeric")
  }
  
  if (length(x) <  3) {
    stop("Input must have at least three numbers")
  }
  z = (x - mean(x)) / sd(x)
  
  
  return(z)
}

z_score(x_vec)
```
Try my function on some other things. These should give error.

```{r, error=TRUE}
z_score(3)
z_score("my name is Jeff")
z_score(mtcars)
z_score(c(TRUE, FALSE, TRUE, TRUE))
```

## Multiple outputs

```{r}
mean_and_sd <- function(x) {
  
  if (!is.numeric(x)) {
    stop("Input must be numeric")
  }
  
  if (length(x) <  3) {
    stop("Input must have at least three numbers")
  }
  
  mean_x = mean(x)
  sd_x = sd(x)
  
  tibble(
    mean = mean_x, 
    sd = sd_x
  )
  
}
```

Check that the function works.

```{r}
x_vec <- rnorm(100, mean = 3, sd = 4)
mean_and_sd(x_vec)
```

## Multiple inputs

I'd like to do this with a function.

```{r}
sim_data <-
  tibble(
    x = rnorm(n = 100, mean = 4, sd = 3)
  )

sim_data %>% 
  summarise(
    mean = mean(x), 
    sd = sd(x)
  )
```


```{r}
sim_mean_sd <- function(samp_size, mu = 3, sigma = 4) {
  sim_data =
  tibble(
    x = rnorm(n = samp_size, mean = mu, sd = sigma)
  )

sim_data %>% 
  summarise(
    mean = mean(x), 
    sd = sd(x)
  )
}

sim_mean_sd(samp_size = 100,mu = 6, sigma = 3)
sim_mean_sd(samp_size = 100)
```

