---
title: "Iteration"
subtitle : "Simulation"
output: github_document
---

```{r setup}
library(tidyverse)
library(rvest)
set.seed(1)
```

## Let's simulate something!

I have a function.
```{r}
sim_mean_sd <- function(samp_size, mu = 3, sigma = 4) {
  sim_data =
  tibble(
    x = rnorm(n = samp_size, mean = mu, sd = sigma)
  )

sim_data %>% 
  summarise(
    mean = mean(x), 
    sd = sd(x)
  )
}
```

I can simulate by running this line.

```{r}
sim_mean_sd(30)
```

## Let's simulate a lot

Let's start with a for loop.

```{r}
output = vector("list", length = 100)

for (i in 1:100) {
  
  output[[i]] = sim_mean_sd(samp_size = 30)

  }

bind_rows(output)
```
Let's use a loop function.

```{r}
sim_results =
rerun(100, sim_mean_sd(samp_size = 30)) %>% 
  bind_rows()
```

Let's look at results.

```{r}
sim_results %>% 
  ggplot(aes(x = mean)) + geom_density()

sim_results %>% 
  summarise(
    avg_samp_mean = mean(mean),
    sd_samp_mean = sd(mean)
  )

sim_results %>% 
  ggplot(aes(x = sd)) + geom_density()
```

